# -*- coding: utf-8 -*-
"""Only_Wigyapan_Dissertation_v5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zExC7BbcHeBasTppVZQYXUjDID_oWkkJ

# Project: Advertiser Retention Intelligence System (ARIS)
**Objective:** Predicting B2B Churn in DOOH Advertising using Proxy ROI Metrics.
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import warnings
import numpy as np
import pandas as pd

warnings.filterwarnings('ignore')

"""
### Step 1: Data Ingestion
We are loading proprietary Salesforce CRM data (2021-2025).
* **Primary Tables:** Accounts (Client Profile), Quotes (Financial History), Posts (Campaign Delivery).
"""

DATA_PATH = '/content/drive/MyDrive/VIT/Project/New folder/'

files = os.listdir(DATA_PATH)
print(f"Total files found: {len(files)}")
print("\nFiles in folder:")
for f in sorted(files):
    size_mb = os.path.getsize(os.path.join(DATA_PATH, f)) / (1024 * 1024)
    print(f" {f:<45} {size_mb:.2f} MB")

accounts = pd.read_csv(DATA_PATH + 'Account.csv', low_memory=False)
acc_device = pd.read_csv(DATA_PATH + 'Account_Device__c.csv', low_memory=False)
devices = pd.read_csv(DATA_PATH + 'Device__c.csv', low_memory=False)
inv = pd.read_csv(DATA_PATH + 'Invoice__c.csv', low_memory=False)
inv_line = pd.read_csv(DATA_PATH + 'Invoice_Line_Item__c.csv', low_memory=False)
pdc = pd.read_csv(DATA_PATH + 'Post_Device_Count__c.csv', low_memory=False)
pd_map = pd.read_csv(DATA_PATH + 'Post_Device__c.csv', low_memory=False)
posts = pd.read_csv(DATA_PATH + 'Post__c.csv', low_memory=False)
txn = pd.read_csv(DATA_PATH + 'Transaction__c.csv', low_memory=False)

print("\n✅ All files loaded. Raw shapes:")
print(f" accounts        : {accounts.shape}")
print(f" acc_device      : {acc_device.shape}")
print(f" devices         : {devices.shape}")
print(f" invoices        : {inv.shape}")
print(f" invoice_lines   : {inv_line.shape}")
print(f" post_dev_count  : {pdc.shape}")
print(f" post_device     : {pd_map.shape}")
print(f" posts           : {posts.shape}")
print(f" transactions    : {txn.shape}")

accounts_clean = accounts[accounts['IsDeleted'] == False][
    ['Id', 'Name', 'Type', 'Industry', 'CreatedDate', 'Email__c', 'Phone']
].copy()
accounts_clean['CreatedDate'] = pd.to_datetime(accounts_clean['CreatedDate'], utc=True, errors='coerce')
accounts_clean = accounts_clean.drop_duplicates(subset='Id')

posts_clean = posts[posts['IsDeleted'] == False][
    ['Id', 'Name', 'CreatedDate', 'Posted_By__c', 'Start_Date__c', 'End_Date__c',
     'Post_Duration__c', 'Post_Industry__c', 'Post_Staus__c', 'Post_Type__c',
     'Slots__c', 'Quote__c']
].copy()
for col in ['CreatedDate', 'Start_Date__c', 'End_Date__c']:
    posts_clean[col] = pd.to_datetime(posts_clean[col], utc=True, errors='coerce')

valid_statuses = ['Posted', 'Completed', 'Active', 'published', 'Inactive', 'InProgress']
posts_clean['Post_Staus__c'] = posts_clean['Post_Staus__c'].astype(str).str.strip()
posts_clean = posts_clean[posts_clean['Post_Staus__c'].isin(valid_statuses)].copy()
posts_clean['Campaign_Duration_Days'] = (
    (posts_clean['End_Date__c'] - posts_clean['Start_Date__c']).dt.days + 1
).clip(lower=1)
posts_clean = posts_clean.drop_duplicates(subset='Id')

pdc_clean = pdc[pdc['IsDeleted'] == False][
    ['Post__c', 'Device__c', 'Post_Count__c', 'Posted_Date__c']
].copy()
pdc_clean.columns = ['Post_Id', 'Device_Id', 'Play_Count', 'Play_Date']
pdc_clean['Play_Date'] = pd.to_datetime(pdc_clean['Play_Date'], utc=True, errors='coerce')
pdc_clean['Play_Count'] = pd.to_numeric(pdc_clean['Play_Count'], errors='coerce').fillna(0).astype(int)
pdc_clean = pdc_clean[pdc_clean['Play_Count'] > 0].drop_duplicates()

pd_map_clean = pd_map[pd_map['IsDeleted'] == False][
    ['Post__c', 'Device__c', 'Post_Device_Status__c']
].copy()
pd_map_clean['Post_Device_Status__c'] = pd_map_clean['Post_Device_Status__c'].astype(str).str.strip()
pd_map_clean = pd_map_clean[
    pd_map_clean['Post_Device_Status__c'].isin(['Active', 'Completed', 'Published', 'Inactive'])
].copy()

screens_booked = pd_map_clean.groupby('Post__c')['Device__c'].nunique().reset_index()
screens_booked.columns = ['Id', 'Screens_Booked']

inv_clean = inv[
    (inv['IsDeleted'] == False) &
    (inv['Status__c'].astype(str).str.strip() != 'Cancelled')
][['Id', 'Quote__c', 'Invoice_Date__c', 'Sub_Total__c', 'Status__c']].copy()

inv_clean['Invoice_Date__c'] = pd.to_datetime(inv_clean['Invoice_Date__c'], utc=True, errors='coerce')
inv_clean['Sub_Total__c'] = pd.to_numeric(inv_clean['Sub_Total__c'], errors='coerce').fillna(0)

inv_line_clean = inv_line[inv_line['IsDeleted'] == False][
    ['Invoice__c', 'Unit_Price__c', 'Months__c']
].copy()
inv_line_clean['Unit_Price__c'] = pd.to_numeric(inv_line_clean['Unit_Price__c'], errors='coerce').fillna(0)
inv_line_clean['Months__c'] = pd.to_numeric(inv_line_clean['Months__c'], errors='coerce').fillna(1)
inv_line_clean['Line_Amount'] = inv_line_clean['Unit_Price__c'] * inv_line_clean['Months__c']

line_totals = inv_line_clean.groupby('Invoice__c')['Line_Amount'].sum().reset_index()
line_totals.columns = ['Id', 'Derived_Amount']

inv_clean = inv_clean.merge(line_totals, on='Id', how='left')
inv_clean['Final_Amount'] = inv_clean['Derived_Amount'].fillna(inv_clean['Sub_Total__c'])

txn_clean = txn[
    (txn['IsDeleted'] == False) &
    (txn['Status__c'].astype(str).str.strip().isin(['Completed', 'Done']))
][['Id', 'Account__c', 'Amount__c', 'Transaction_Date__c', 'Type__c']].copy()

txn_clean['Transaction_Date__c'] = pd.to_datetime(txn_clean['Transaction_Date__c'], utc=True, errors='coerce')
txn_clean['Amount__c'] = pd.to_numeric(txn_clean['Amount__c'], errors='coerce').fillna(0)

devices_clean = devices[devices['IsDeleted'] == False][
    ['Id', 'Name', 'Area__c', 'City__c', 'Device_Status__c', 'Slot_Size__c']
].copy()

acc_dev_clean = acc_device[acc_device['IsDeleted'] == False][
    ['Id', 'Device__c', 'Account_Device_Status__c', 'Assigned_to__c', 'Start_Date__c', 'End_Date__c']
].copy()
for col in ['Start_Date__c', 'End_Date__c']:
    acc_dev_clean[col] = pd.to_datetime(acc_dev_clean[col], utc=True, errors='coerce')

print("\n" + "=" * 55)
print("DATA CLEANING SUMMARY — WIGYAPAN DOOH CRM")
print("=" * 55)
summary = {
    'Account': (len(accounts), len(accounts_clean)),
    'Post__c': (len(posts), len(posts_clean)),
    'Post_Device_Count': (len(pdc), len(pdc_clean)),
    'Post_Device': (len(pd_map), len(pd_map_clean)),
    'Invoice': (len(inv), len(inv_clean)),
    'Invoice_Line_Item': (len(inv_line), len(inv_line_clean)),
    'Transaction': (len(txn), len(txn_clean)),
    'Device': (len(devices), len(devices_clean)),
    'Account_Device': (len(acc_device), len(acc_dev_clean)),
}
print(f"\n{'Object':<25} {'Raw':>8} {'Clean':>8} {'Dropped':>8}")
print("-" * 55)
for obj, (raw, clean) in summary.items():
    print(f"{obj:<25} {raw:>8} {clean:>8} {raw-clean:>8}")
print("=" * 55)

junk_names = [
    'Salesforce', 'Google', 'Hathway Internet', 'Wigyapan', 'Wigyapan Ads',
    'Irani Cafe', 'Durga Cafe', 'Relax Pav Bhaji', 'Hotel Tilak', 'Gems Hospital',
    'Chai Bar', 'Nitro Gym', 'Goodluck Cafe', 'SA Dosa Cafe', 'Bedekar Misal',
    'Deccan Gymkhana', 'Hotel Yatrik', 'Its Yummy Cafe', 'Lyf Fitness',
    '11 East Street Cafe', 'Vishnuji Ki Rasoi', 'Global Port', 'IMDR',
    "Vikram's Fitness Studio"
]
valid_account_types = ['Customer', 'Customer Plus', 'Promoter']

accounts_valid = accounts_clean[
    ((accounts_clean['Type'].isin(valid_account_types)) | (accounts_clean['Type'].isna())) &
    (~accounts_clean['Name'].isin(junk_names))
].copy()

valid_account_ids = set(accounts_valid['Id'])
posts_clean = posts_clean[posts_clean['Posted_By__c'].isin(valid_account_ids)].copy()

print(f"\nAccounts: {len(accounts_clean)} -> {len(accounts_valid)} valid advertisers")
print(f"Posts after advertiser filter: {len(posts_clean)}")
print(f"Unique advertisers in posts: {posts_clean['Posted_By__c'].nunique()}")


# ── Merge duplicate accounts ──────────────────────────────────────────────────
dup_merge = {
    accounts_valid[accounts_valid['Name'] == 'Mathesul']['Id'].values[0]:
        accounts_valid[accounts_valid['Name'] == 'DR Mathesul']['Id'].values[0],

    accounts_valid[
        (accounts_valid['Name'] == 'Triumph Motors') &
        (accounts_valid['Id'] != accounts_valid[
            accounts_valid['Name'] == 'Triumph Motors'
        ]['Id'].values[-1])
    ]['Id'].values[0]:
        accounts_valid[accounts_valid['Name'] == 'Triumph Motors']['Id'].values[-1],
}

# Apply to posts only (inv_clean has no account column)
posts_clean['Posted_By__c'] = posts_clean['Posted_By__c'].replace(dup_merge)

# Remove duplicate rows from accounts_valid
accounts_valid = accounts_valid[~accounts_valid['Id'].isin(dup_merge.keys())].copy()

print(f"Duplicate accounts merged. accounts_valid: {len(accounts_valid)}")
print(f"Posts after merge: {len(posts_clean)}")
print(f"Unique advertisers after merge: {posts_clean['Posted_By__c'].nunique()}")



# ── Manual Monetary corrections ───────────────────────────────────────────────
monetary_corrections = {
    'DR Mathesul'                        : 20000,
    'Jogeshwari Hotel'                   : 5000,
    'Hexa Fin'                           : 10000,
    'Shri Jogeshwari Silk and Sarees'    : 10000,
    'MFI Film and TV Institute'          : 25000,
    'Mahesh Purandare'                   : 7000,
    'Surprise Interiors'                 : 30000,
    'Lead Media'                         : 25000,
    'Games Mela'                         : 10000,
    'BlueRamp'                           : 35000,
    'Kotibhaskar Infrastructures Pvt Ltd': 48000,
    'Healthy Jeevan'                     : 10000,
    'Autosol'                            : 500,
    'Transglobe Education'               : 22000,
    'Tilak Maharashtra Vidyapeeth'       : 35000,
    'Franco-Indian Institute'            : 20000,
    'Adwitiya'                           : 35000,
    'Zubar'                              : 5000,
    'The Middle Road'                    : 6000,
    'Bling Auto'                         : 36000,
    'Picture Clicker'                    : 20000,
    'Reshma'                             : 500,
    'Brevistay Hospitality Pvt Ltd'      : 20000,
    'Fateh Education'                    : 20000,
    'Crossfit Bold Heart'                : 18000,
    'Rajyog Masale'                      : 26000,
    'Soil to Soul Farm'                  : 2000,
    'Konkan County'                      : 2000,
}

# ── Remove Digi Roister entirely ──────────────────────────────────────────────
remove_names = ['Digi Roister']
remove_ids = set(accounts_valid[accounts_valid['Name'].isin(remove_names)]['Id'])
accounts_valid = accounts_valid[~accounts_valid['Id'].isin(remove_ids)].copy()
posts_clean = posts_clean[~posts_clean['Posted_By__c'].isin(remove_ids)].copy()

print(f"Removed: {remove_names}")
print(f"accounts_valid: {len(accounts_valid)}")
print(f"Unique advertisers in posts: {posts_clean['Posted_By__c'].nunique()}")

"""# Step 2: Derive DOOH Metrics from Play Telemetry"""

play_agg = pdc_clean.groupby('Post_Id').agg(
    Actual_Plays=('Play_Count', 'sum'),
    Play_Days=('Play_Date', 'nunique'),
    Actual_Screens=('Device_Id', 'nunique')
).reset_index().rename(columns={'Post_Id': 'Id'})

daily_plays = pdc_clean.groupby(['Post_Id', 'Play_Date'])['Play_Count'].sum().reset_index()
peak_daily = daily_plays.groupby('Post_Id')['Play_Count'].max().reset_index()
peak_daily.columns = ['Id', 'Peak_Daily_Plays']

posts_fe = posts_clean.merge(screens_booked, on='Id', how='left')
posts_fe['Campaign_Duration_Days'] = pd.to_numeric(posts_fe['Campaign_Duration_Days'], errors='coerce').fillna(1)
posts_fe['Screens_Booked'] = pd.to_numeric(posts_fe['Screens_Booked'], errors='coerce').fillna(1)

posts_fe = posts_fe.merge(play_agg, on='Id', how='left')
posts_fe = posts_fe.merge(peak_daily, on='Id', how='left')
posts_fe[['Actual_Plays', 'Play_Days', 'Actual_Screens', 'Peak_Daily_Plays']] = (
    posts_fe[['Actual_Plays', 'Play_Days', 'Actual_Screens', 'Peak_Daily_Plays']].fillna(0)
)

posts_fe['Expected_Plays'] = (
    posts_fe['Peak_Daily_Plays'] * posts_fe['Campaign_Duration_Days'] * posts_fe['Screens_Booked']
).clip(lower=1)

posts_fe['Delivery_Rate'] = (posts_fe['Actual_Plays'] / posts_fe['Expected_Plays']).clip(0, 1)
posts_fe['Continuity_Score'] = np.where(
    posts_fe['Campaign_Duration_Days'] > 0,
    posts_fe['Play_Days'] / posts_fe['Campaign_Duration_Days'],
    0
).clip(0, 1)
posts_fe['Screen_Spread'] = np.where(
    posts_fe['Screens_Booked'] > 0,
    posts_fe['Actual_Screens'] / posts_fe['Screens_Booked'],
    0
).clip(0, 1)
posts_fe['Slots_Consumed'] = posts_fe['Actual_Plays'].astype(int)

print(f"\nposts_fe shape: {posts_fe.shape}")
print(f"Unique advertisers: {posts_fe['Posted_By__c'].nunique()}")

"""# Step 3: Engineering the 'Churn' Label
**The 365-Day Rule:** Following B2B industry benchmarks, a client is labeled as **Churned (1)** if their last transaction was >365 days ago.
"""

SNAPSHOT_DATE = pd.Timestamp('2025-03-31', tz='UTC')

post_quote = posts_clean[['Posted_By__c', 'Quote__c']].dropna(subset=['Quote__c'])
inv_quote = inv_clean[['Id', 'Quote__c', 'Final_Amount', 'Invoice_Date__c']].copy()
post_invoice = post_quote.merge(inv_quote, on='Quote__c', how='left')

monetary_df = post_invoice.groupby('Posted_By__c').agg(
    Monetary=('Final_Amount', 'sum'),
    Last_Invoice=('Invoice_Date__c', 'max')
).reset_index().rename(columns={'Posted_By__c': 'Id'})

freq_df = posts_clean.groupby('Posted_By__c').agg(
    Frequency=('Id', 'nunique'),
    Last_Purchase=('Start_Date__c', 'max')
).reset_index().rename(columns={'Posted_By__c': 'Id'})

rfm = accounts_valid[['Id', 'Name']].merge(freq_df, on='Id', how='inner')
rfm = rfm.merge(monetary_df[['Id', 'Monetary']], on='Id', how='left')

rfm['Monetary'] = rfm['Monetary'].fillna(0)
# ── Apply manual Monetary corrections ────────────────────────────────────────
rfm['Monetary'] = rfm.apply(
    lambda row: monetary_corrections.get(row['Name'], row['Monetary']),
    axis=1
)
print("Monetary corrections applied.")
print(f"Zero Monetary remaining: {(rfm['Monetary'] == 0).sum()}")

rfm['Last_Purchase'] = pd.to_datetime(rfm['Last_Purchase'], utc=True, errors='coerce')
rfm['Recency'] = (SNAPSHOT_DATE - rfm['Last_Purchase']).dt.days

rfm['Churned'] = ((rfm['Recency'] > 365) & (rfm['Frequency'] < 3)).astype(int)

rfm['R_Score'] = pd.qcut(rfm['Recency'].rank(method='first'), 5, labels=[5, 4, 3, 2, 1]).astype(int)
rfm['F_Score'] = pd.cut(
    rfm['Frequency'],
    bins=[0, 1, 2, 3, 5, rfm['Frequency'].max() + 1],
    labels=[1, 2, 3, 4, 5],
    right=True
).astype(int)
rfm['M_Score'] = pd.qcut(rfm['Monetary'].rank(method='first'), 5, labels=[1, 2, 3, 4, 5]).astype(int)
rfm['RFM_Score'] = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str) + rfm['M_Score'].astype(str)

def rfm_segment(row):
    r, f = row['R_Score'], row['F_Score']
    if r >= 4 and f >= 4:
        return 'Champions'
    elif r >= 3 and f >= 3:
        return 'Loyal Customers'
    elif r >= 4 and f <= 2:
        return 'Promising'
    elif r <= 2 and f >= 3:
        return 'Cannot Lose Them'
    elif r <= 2 and f <= 2:
        return 'Lost'
    else:
        return 'At Risk'

rfm['Segment'] = rfm.apply(rfm_segment, axis=1)

print(f"\nRFM table shape: {rfm.shape}")
print(f"Churn distribution: {rfm['Churned'].value_counts().to_dict()}")

"""# Step 4: Proxy ROI Metrics"""

impressions = pdc_clean.groupby('Post_Id').agg(
    Total_Impressions=('Play_Count', 'sum'),
    Unique_Devices=('Device_Id', 'nunique')
).reset_index().rename(columns={'Post_Id': 'Id'})

post_impressions = posts_clean[['Id', 'Posted_By__c']].merge(impressions, on='Id', how='left')
post_impressions[['Total_Impressions', 'Unique_Devices']] = (
    post_impressions[['Total_Impressions', 'Unique_Devices']].fillna(0)
)

roi_proxy = post_impressions.groupby('Posted_By__c').agg(
    Total_Impressions=('Total_Impressions', 'sum'),
    Total_Campaign_Entries=('Id', 'nunique'),
    Unique_Devices=('Unique_Devices', 'max')
).reset_index().rename(columns={'Posted_By__c': 'Id'})

roi_proxy['Total_Impressions'] = roi_proxy['Total_Impressions'].astype(int)

print(f"\nROI Proxy shape: {roi_proxy.shape}")

"""# Step 5: Data Summary and Class Imbalance


"""

dooh_client = posts_fe.groupby('Posted_By__c').agg(
    Avg_Delivery_Rate=('Delivery_Rate', 'mean'),
    Avg_Continuity_Score=('Continuity_Score', 'mean'),
    Avg_Screen_Spread=('Screen_Spread', 'mean'),
    Avg_Campaign_Duration=('Campaign_Duration_Days', 'mean'),
    Total_Slots_Consumed=('Slots_Consumed', 'sum')
).reset_index().rename(columns={'Posted_By__c': 'Id'})

print(f"\nDOOH client features shape: {dooh_client.shape}")
print(rfm['Churned'].value_counts())

"""# # Step 6: Build Master Feature Table"""

master = rfm.merge(roi_proxy, on='Id', how='left')
master = master.merge(dooh_client, on='Id', how='left')

fill_cols = [
    'Total_Impressions', 'Total_Campaign_Entries', 'Unique_Devices',
    'Avg_Delivery_Rate', 'Avg_Continuity_Score', 'Avg_Screen_Spread',
    'Avg_Campaign_Duration', 'Total_Slots_Consumed'
]
master[fill_cols] = master[fill_cols].fillna(0)

master['Total_Impressions'] = master['Total_Impressions'].astype(int)
master['Total_Campaign_Entries'] = master['Total_Campaign_Entries'].astype(int)
master['Unique_Devices'] = master['Unique_Devices'].astype(int)
master['Total_Slots_Consumed'] = master['Total_Slots_Consumed'].astype(int)

print(f"\nMaster table shape: {master.shape}")
print(f"Missing values: {master.isnull().sum().sum()}")
print(f"Churn distribution: {master['Churned'].value_counts().to_dict()}")
display(master.head(3))

"""# Step 7: Model Training"""

"""Step 7: Model Training — No SMOTE (class_weight='balanced' handles imbalance)"""

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier

features = [
    'Frequency', 'Monetary', 'F_Score', 'M_Score',
    'Total_Impressions', 'Total_Campaign_Entries', 'Unique_Devices',
    'Avg_Delivery_Rate', 'Avg_Continuity_Score',
    'Avg_Screen_Spread', 'Avg_Campaign_Duration',
    'Total_Slots_Consumed'
]

X = master[features].copy()
y = master['Churned'].copy()

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# --- Logistic Regression ---
scaler_ns = StandardScaler()
X_train_sc = scaler_ns.fit_transform(X_train)
X_test_sc  = scaler_ns.transform(X_test)
X_scaled_all = scaler_ns.fit_transform(X)

lr_ns = LogisticRegression(random_state=42, max_iter=5000, solver='lbfgs')
lr_ns.fit(X_train_sc, y_train)
lr_ns_auc = roc_auc_score(y_test, lr_ns.predict_proba(X_test_sc)[:, 1])
lr_ns_cv  = cross_val_score(
    LogisticRegression(random_state=42, max_iter=5000, solver='lbfgs'),
    X_scaled_all, y, cv=cv, scoring='roc_auc'
)

# --- Random Forest (Selected Model) ---
rf_ns = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
rf_ns.fit(X_train, y_train)
rf_ns_auc = roc_auc_score(y_test, rf_ns.predict_proba(X_test)[:, 1])
rf_ns_cv  = cross_val_score(rf_ns, X, y, cv=cv, scoring='roc_auc')

# --- XGBoost ---
xgb_ns = XGBClassifier(
    n_estimators=100, max_depth=4, learning_rate=0.1,
    random_state=42, eval_metric='logloss', verbosity=0
)
xgb_ns.fit(X_train, y_train)
xgb_ns_pred = xgb_ns.predict(X_test)
xgb_ns_auc  = roc_auc_score(y_test, xgb_ns.predict_proba(X_test)[:, 1])
xgb_ns_cv   = cross_val_score(xgb_ns, X, y, cv=cv, scoring='roc_auc')

# --- Model Comparison ---
print("\n========== MODEL COMPARISON — NO SMOTE ==========")
print(f"{'Model':<25} {'Test AUC':>10} {'CV AUC':>10} {'CV Std':>8}")
print(f"{'Logistic Regression':<25} {lr_ns_auc:>10.4f} {lr_ns_cv.mean():>10.4f} {lr_ns_cv.std():>8.4f}")
print(f"{'Random Forest':<25} {rf_ns_auc:>10.4f} {rf_ns_cv.mean():>10.4f} {rf_ns_cv.std():>8.4f}")
print(f"{'XGBoost':<25} {xgb_ns_auc:>10.4f} {xgb_ns_cv.mean():>10.4f} {xgb_ns_cv.std():>8.4f}")

print("\n--- Random Forest Classification Report (Selected Model) ---")
rf_ns_pred = rf_ns.predict(X_test)
print(classification_report(y_test, rf_ns_pred))

feat_imp_rf_ns = pd.DataFrame({
    'Feature': features,
    'RF_Importance': rf_ns.feature_importances_
}).sort_values('RF_Importance', ascending=False)
print("\n--- Random Forest Feature Importance ---")
print(feat_imp_rf_ns.to_string(index=False))

"""#Step 8: Churn Probability Scoring"""

master['Churn_Probability'] = rf_ns.predict_proba(X)[:, 1]
master['Churn_Prediction'] = rf_ns.predict(X)
master['Risk_Tier'] = pd.cut(
    master['Churn_Probability'],
    bins=[0, 0.35, 0.65, 1.0],
    labels=['Low Risk', 'Medium Risk', 'High Risk'],
    include_lowest=True
)

print("\nRisk Tier Distribution:")
print(master['Risk_Tier'].value_counts().sort_index())

top_risk = master[
    ['Name', 'Segment', 'Churn_Probability', 'Risk_Tier',
     'Frequency', 'Monetary', 'Avg_Continuity_Score', 'Avg_Delivery_Rate']
].sort_values('Churn_Probability', ascending=False)

print("\nTop 10 At-Risk Clients:")
display(top_risk.head(10))

"""#
Step 9: Final Output
"""

# Score all 72 clients
master['Churn_Probability'] = rf_ns.predict_proba(X)[:, 1]
master['Churn_Prediction'] = rf_ns.predict(X)

# Risk tiers
master['Risk_Tier'] = pd.cut(
    master['Churn_Probability'],
    bins=[0, 0.35, 0.65, 1.0],
    labels=['Low Risk', 'Medium Risk', 'High Risk']
)

print("Risk Tier Distribution:")
print(master['Risk_Tier'].value_counts().sort_index())

# Top 10 highest churn risk clients
top_risk = master[['Name', 'Segment', 'Churn_Probability', 'Risk_Tier',
                    'Frequency', 'Monetary', 'Avg_Continuity_Score',
                    'Avg_Delivery_Rate']].sort_values('Churn_Probability', ascending=False)
print("\nTop 10 At-Risk Clients:")
display(top_risk.head(10))

"""# Step 9: Final Output"""

"""Step 9: Final Output"""
import os
os.makedirs('output', exist_ok=True)

master.to_csv('output/churn_scored_clients.csv', index=False)
top_risk.head(20).to_csv('output/top20_at_risk_clients.csv', index=False)

print("Files saved:")
print(" - output/churn_scored_clients.csv")
print(" - output/top20_at_risk_clients.csv")
print(f"\nTotal clients scored : {len(master)}")
print(f"High Risk            : {(master['Risk_Tier'] == 'High Risk').sum()}")
print(f"Medium Risk          : {(master['Risk_Tier'] == 'Medium Risk').sum()}")
print(f"Low Risk             : {(master['Risk_Tier'] == 'Low Risk').sum()}")
print(f"Model Test AUC : {rf_ns_auc:.4f}")
print(f"Model CV AUC : {rf_ns_cv.mean():.4f} ± {rf_ns_cv.std():.4f}")

"""# Step 10: Dissertation Visualisation Pack"""

# Step 10: Dissertation Visualisation Pack
import plotly.graph_objects as go
import os
os.makedirs("output", exist_ok=True)

BRAND = "#1B4F72"
RED   = "#C0392B"
AMBER = "#D4AC0D"
GREEN = "#1E8449"
BG    = "#F8F9FA"
FONT  = "Inter, Arial, sans-serif"

# --- Fig 1: Random Forest Feature Importance ---
feat_imp_rf_sorted = feat_imp_rf_ns.sort_values("RF_Importance")
fig1 = go.Figure(go.Bar(
    x=feat_imp_rf_sorted["RF_Importance"],
    y=feat_imp_rf_sorted["Feature"],
    orientation="h",
    marker_color=[RED if v > 0.1 else BRAND if v > 0.03 else "#AEB6BF"
                  for v in feat_imp_rf_sorted["RF_Importance"]],
    text=[f"{v:.1%}" for v in feat_imp_rf_sorted["RF_Importance"]],
    textposition="outside"
))
fig1.update_layout(
    title=dict(text="Random Forest Feature Importance – Churn Prediction", font_size=16, font_family=FONT),
    xaxis_title="Importance Score", yaxis_title="",
    plot_bgcolor=BG, paper_bgcolor="white",
    height=480, width=780,
    margin=dict(l=200, r=80, t=60, b=50),
    font=dict(family=FONT, size=12)
)
fig1.write_html("output/fig1_feature_importance.html")
fig1.show()
print("Fig 1 saved")

# --- Fig 2: Risk Tier Donut ---
tier_counts = master["Risk_Tier"].value_counts().sort_index()
fig2 = go.Figure(go.Pie(
    labels=tier_counts.index,
    values=tier_counts.values,
    hole=0.55,
    marker_colors=[GREEN, AMBER, RED],
    textinfo="label+percent",
    textfont_size=13,
    pull=[0, 0, 0.05]
))
fig2.update_layout(
    title=dict(text=f"Client Risk Tier Distribution (n={len(master)})", font_size=16, font_family=FONT),
    annotations=[dict(text=f"{len(master)}<br>Clients", x=0.5, y=0.5,
                      font_size=14, font_family=FONT, showarrow=False)],
    paper_bgcolor="white", height=440, width=540,
    margin=dict(l=40, r=40, t=60, b=40),
    font=dict(family=FONT)
)
fig2.write_html("output/fig2_risk_tier_donut.html")
fig2.show()
print("Fig 2 saved")

# --- Fig 3: Churn Probability Distribution ---
fig3 = go.Figure()
for churn_val, color, label in [(0, GREEN, "Active"), (1, RED, "Churned")]:
    subset = master[master["Churned"] == churn_val]["Churn_Probability"]
    fig3.add_trace(go.Histogram(x=subset, nbinsx=15, name=label,
                                marker_color=color, opacity=0.72))
fig3.add_vline(x=0.65, line_dash="dash", line_color=AMBER,
               annotation_text="High Risk Threshold (0.65)",
               annotation_position="top right")
fig3.update_layout(
    title=dict(text="Churn Probability Distribution by Actual Outcome", font_size=16, font_family=FONT),
    xaxis_title="Churn Probability", yaxis_title="Count",
    barmode="overlay", plot_bgcolor=BG, paper_bgcolor="white",
    height=420, width=720, margin=dict(l=60, r=40, t=60, b=50),
    legend=dict(x=0.02, y=0.98), font=dict(family=FONT, size=12)
)
fig3.write_html("output/fig3_churn_prob_dist.html")
fig3.show()
print("Fig 3 saved")

# --- Fig 4: RFM Segment × Risk Tier Heatmap ---
seg_risk = master.groupby(["Segment", "Risk_Tier"]).size().unstack(fill_value=0)
for col in ["Low Risk", "Medium Risk", "High Risk"]:
    if col not in seg_risk.columns:
        seg_risk[col] = 0
seg_risk = seg_risk[["Low Risk", "Medium Risk", "High Risk"]]
fig4 = go.Figure(go.Heatmap(
    z=seg_risk.values,
    x=seg_risk.columns.tolist(),
    y=seg_risk.index.tolist(),
    colorscale=[[0, "#EBF5FB"], [0.5, AMBER], [1, RED]],
    text=seg_risk.values,
    texttemplate="%{text}",
    textfont_size=14,
    showscale=True
))
fig4.update_layout(
    title=dict(text="RFM Segment × Churn Risk Heatmap", font_size=16, font_family=FONT),
    xaxis_title="Risk Tier", yaxis_title="RFM Segment",
    plot_bgcolor=BG, paper_bgcolor="white",
    height=440, width=680,
    margin=dict(l=160, r=40, t=60, b=60),
    font=dict(family=FONT, size=12)
)
fig4.write_html("output/fig4_rfm_risk_heatmap.html")
fig4.show()
print("Fig 4 saved")

# --- Fig 5: Model Comparison (CV AUC) ---
models  = ["Logistic Regression", "Random Forest", "XGBoost"]
cv_aucs = [lr_ns_cv.mean(), rf_ns_cv.mean(), xgb_ns_cv.mean()]
cv_stds = [lr_ns_cv.std(),  rf_ns_cv.std(),  xgb_ns_cv.std()]
fig5 = go.Figure(go.Bar(
    name="CV AUC (5-Fold)",
    x=models, y=cv_aucs,
    marker_color=[BRAND, RED, BRAND],
    opacity=0.9,
    text=[f"{v:.3f}" for v in cv_aucs],
    textposition="outside",
    error_y=dict(type="data", array=cv_stds, visible=True)
))
fig5.update_layout(
    title=dict(text="Model Comparison – 5-Fold Cross-Validated AUC", font_size=16, font_family=FONT),
    yaxis=dict(range=[0.7, 1.05], title="CV AUC Score"),
    plot_bgcolor=BG, paper_bgcolor="white",
    height=440, width=720,
    margin=dict(l=60, r=40, t=60, b=50),
    font=dict(family=FONT, size=12)
)
fig5.write_html("output/fig5_model_comparison.html")
fig5.show()
print("Fig 5 saved")

print("\n✅ All 5 figures saved to output/")